





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace ProjectPortal.Feature.Alerts
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}

namespace ProjectPortal.Feature.Alerts
{


 	/// <summary>
	/// IBaseTemplate Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Common/BaseTemplate</para>	
	/// <para>ID: 07632344-b37d-47bb-8376-6fd1a67b3ef9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBaseTemplateConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBaseTemplate : IGlassBase 
	{
				}


	public static partial class IBaseTemplateConstants{

			public const string TemplateIdString = "07632344-b37d-47bb-8376-6fd1a67b3ef9";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "BaseTemplate";

			

	}

	
	/// <summary>
	/// BaseTemplate
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Common/BaseTemplate</para>	
	/// <para>ID: 07632344-b37d-47bb-8376-6fd1a67b3ef9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBaseTemplateConstants.TemplateIdString)] //, Cachable = true
	public partial class BaseTemplate  : GlassBase, IBaseTemplate 
	{
	   
			
	}
}
namespace ProjectPortal.Feature.Alerts
{


 	/// <summary>
	/// IAlert_Severity_DataSource Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alert Severity DataSource</para>	
	/// <para>ID: 17e0df31-fe20-4881-b521-bccb5af0ec21</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlert_Severity_DataSourceConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAlert_Severity_DataSource : IGlassBase , global::ProjectPortal.Feature.Alerts.I_AlertSeverity
	{
				}


	public static partial class IAlert_Severity_DataSourceConstants{

			public const string TemplateIdString = "17e0df31-fe20-4881-b521-bccb5af0ec21";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Alert Severity DataSource";

			

	}

	
	/// <summary>
	/// Alert_Severity_DataSource
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alert Severity DataSource</para>	
	/// <para>ID: 17e0df31-fe20-4881-b521-bccb5af0ec21</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlert_Severity_DataSourceConstants.TemplateIdString)] //, Cachable = true
	public partial class Alert_Severity_DataSource  : GlassBase, IAlert_Severity_DataSource 
	{
	   
			
	}
}
namespace ProjectPortal.Feature.Alerts
{


 	/// <summary>
	/// IAlert_Severity_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alert Severity Folder</para>	
	/// <para>ID: 225ed394-ac21-4967-abbf-743d6daf9270</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlert_Severity_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAlert_Severity_Folder : IGlassBase 
	{
				}


	public static partial class IAlert_Severity_FolderConstants{

			public const string TemplateIdString = "225ed394-ac21-4967-abbf-743d6daf9270";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Alert Severity Folder";

			

	}

	
	/// <summary>
	/// Alert_Severity_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alert Severity Folder</para>	
	/// <para>ID: 225ed394-ac21-4967-abbf-743d6daf9270</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlert_Severity_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Alert_Severity_Folder  : GlassBase, IAlert_Severity_Folder 
	{
	   
			
	}
}
namespace ProjectPortal.Feature.Alerts
{


 	/// <summary>
	/// IAlert_Settings Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alert Settings</para>	
	/// <para>ID: 41dfdb63-c7ca-4807-8910-1077f13dde2d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlert_SettingsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAlert_Settings : IGlassBase 
	{
								/// <summary>
					/// The Alerts Location field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 45a0ad96-3ee7-4f7a-9ccb-54edc247a6c0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAlert_SettingsConstants.Alerts_LocationFieldName)]
					Link Alerts_Location  {get; set;}
			
				}


	public static partial class IAlert_SettingsConstants{

			public const string TemplateIdString = "41dfdb63-c7ca-4807-8910-1077f13dde2d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Alert Settings";

					
			public static readonly ID Alerts_LocationFieldId = new ID("45a0ad96-3ee7-4f7a-9ccb-54edc247a6c0");
			public const string Alerts_LocationFieldName = "Alerts Location";
			
			

	}

	
	/// <summary>
	/// Alert_Settings
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alert Settings</para>	
	/// <para>ID: 41dfdb63-c7ca-4807-8910-1077f13dde2d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlert_SettingsConstants.TemplateIdString)] //, Cachable = true
	public partial class Alert_Settings  : GlassBase, IAlert_Settings 
	{
	   
						/// <summary>
				/// The Alerts Location field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 45a0ad96-3ee7-4f7a-9ccb-54edc247a6c0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAlert_SettingsConstants.Alerts_LocationFieldName)]
				public virtual Link Alerts_Location  {get; set;}
					
			
	}
}
namespace ProjectPortal.Feature.Alerts
{


 	/// <summary>
	/// IAlerts_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alerts Folder</para>	
	/// <para>ID: 77349166-96b7-42eb-b752-acdcd608c824</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlerts_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAlerts_Folder : IGlassBase 
	{
				}


	public static partial class IAlerts_FolderConstants{

			public const string TemplateIdString = "77349166-96b7-42eb-b752-acdcd608c824";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Alerts Folder";

			

	}

	
	/// <summary>
	/// Alerts_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alerts Folder</para>	
	/// <para>ID: 77349166-96b7-42eb-b752-acdcd608c824</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlerts_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Alerts_Folder  : GlassBase, IAlerts_Folder 
	{
	   
			
	}
}
namespace ProjectPortal.Feature.Alerts
{


 	/// <summary>
	/// IAlert_DataSource Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alert DataSource</para>	
	/// <para>ID: d9577b16-776f-48c3-b2f8-e31514acd492</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlert_DataSourceConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAlert_DataSource : IGlassBase , global::ProjectPortal.Feature.Alerts.I_Alert
	{
				}


	public static partial class IAlert_DataSourceConstants{

			public const string TemplateIdString = "d9577b16-776f-48c3-b2f8-e31514acd492";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Alert DataSource";

					
			public static readonly ID Alert_DescriptionFieldId = new ID("413bae14-4b52-4429-96cb-eb84d3841d1f");
			public const string Alert_DescriptionFieldName = "Alert Description";
			
					
			public static readonly ID Alert_TitleFieldId = new ID("ea19cfe8-8026-497a-9652-83c1712dae9d");
			public const string Alert_TitleFieldName = "Alert Title";
			
					
			public static readonly ID IsActiveFieldId = new ID("c6f7c6c4-74ef-4ae5-84da-b7a0fa159316");
			public const string IsActiveFieldName = "IsActive";
			
					
			public static readonly ID SeverityFieldId = new ID("891f95ce-edbe-496c-a34b-2e0fcb085289");
			public const string SeverityFieldName = "Severity";
			
					
			public static readonly ID Valid_FromFieldId = new ID("a08ea501-d339-4f3d-9da3-cbff8088c76c");
			public const string Valid_FromFieldName = "Valid From";
			
					
			public static readonly ID Valid_ToFieldId = new ID("5758f22c-2394-42ae-94e8-05913ea009c8");
			public const string Valid_ToFieldName = "Valid To";
			
			

	}

	
	/// <summary>
	/// Alert_DataSource
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/Alert DataSource</para>	
	/// <para>ID: d9577b16-776f-48c3-b2f8-e31514acd492</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAlert_DataSourceConstants.TemplateIdString)] //, Cachable = true
	public partial class Alert_DataSource  : GlassBase, IAlert_DataSource 
	{
	   
						/// <summary>
				/// The Alert Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 413bae14-4b52-4429-96cb-eb84d3841d1f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAlert_DataSourceConstants.Alert_DescriptionFieldName)]
				public virtual string Alert_Description  {get; set;}
					
						/// <summary>
				/// The Alert Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ea19cfe8-8026-497a-9652-83c1712dae9d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAlert_DataSourceConstants.Alert_TitleFieldName)]
				public virtual string Alert_Title  {get; set;}
					
						/// <summary>
				/// The IsActive field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: c6f7c6c4-74ef-4ae5-84da-b7a0fa159316</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAlert_DataSourceConstants.IsActiveFieldName)]
				public virtual bool IsActive  {get; set;}
					
						/// <summary>
				/// The Severity field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// <para>Field ID: 891f95ce-edbe-496c-a34b-2e0fcb085289</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAlert_DataSourceConstants.SeverityFieldName)]
				public virtual string Severity  {get; set;}
					
						/// <summary>
				/// The Valid From field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: a08ea501-d339-4f3d-9da3-cbff8088c76c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAlert_DataSourceConstants.Valid_FromFieldName)]
				public virtual DateTime Valid_From  {get; set;}
					
						/// <summary>
				/// The Valid To field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: 5758f22c-2394-42ae-94e8-05913ea009c8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAlert_DataSourceConstants.Valid_ToFieldName)]
				public virtual DateTime Valid_To  {get; set;}
					
			
	}
}
namespace ProjectPortal.Feature.Alerts
{


 	/// <summary>
	/// I_AlertSeverity Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/_AlertSeverity</para>	
	/// <para>ID: ed369542-ad08-40ae-9372-96030765def1</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_AlertSeverityConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_AlertSeverity : IGlassBase 
	{
				}


	public static partial class I_AlertSeverityConstants{

			public const string TemplateIdString = "ed369542-ad08-40ae-9372-96030765def1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_AlertSeverity";

			

	}

	
	/// <summary>
	/// _AlertSeverity
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/_AlertSeverity</para>	
	/// <para>ID: ed369542-ad08-40ae-9372-96030765def1</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_AlertSeverityConstants.TemplateIdString)] //, Cachable = true
	public partial class _AlertSeverity  : GlassBase, I_AlertSeverity 
	{
	   
			
	}
}
namespace ProjectPortal.Feature.Alerts
{


 	/// <summary>
	/// I_Alert Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/_Alert</para>	
	/// <para>ID: fce37f72-5db6-4ba6-9591-2ef80648a46e</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_AlertConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Alert : IGlassBase 
	{
								/// <summary>
					/// The Alert Description field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 413bae14-4b52-4429-96cb-eb84d3841d1f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_AlertConstants.Alert_DescriptionFieldName)]
					string Alert_Description  {get; set;}
			
								/// <summary>
					/// The Alert Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ea19cfe8-8026-497a-9652-83c1712dae9d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_AlertConstants.Alert_TitleFieldName)]
					string Alert_Title  {get; set;}
			
								/// <summary>
					/// The IsActive field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: c6f7c6c4-74ef-4ae5-84da-b7a0fa159316</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_AlertConstants.IsActiveFieldName)]
					bool IsActive  {get; set;}
			
								/// <summary>
					/// The Severity field.
					/// <para></para>
					/// <para>Field Type: Droplist</para>		
					/// <para>Field ID: 891f95ce-edbe-496c-a34b-2e0fcb085289</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_AlertConstants.SeverityFieldName)]
					string Severity  {get; set;}
			
								/// <summary>
					/// The Valid From field.
					/// <para></para>
					/// <para>Field Type: Datetime</para>		
					/// <para>Field ID: a08ea501-d339-4f3d-9da3-cbff8088c76c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_AlertConstants.Valid_FromFieldName)]
					DateTime Valid_From  {get; set;}
			
								/// <summary>
					/// The Valid To field.
					/// <para></para>
					/// <para>Field Type: Datetime</para>		
					/// <para>Field ID: 5758f22c-2394-42ae-94e8-05913ea009c8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_AlertConstants.Valid_ToFieldName)]
					DateTime Valid_To  {get; set;}
			
				}


	public static partial class I_AlertConstants{

			public const string TemplateIdString = "fce37f72-5db6-4ba6-9591-2ef80648a46e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Alert";

					
			public static readonly ID Alert_DescriptionFieldId = new ID("413bae14-4b52-4429-96cb-eb84d3841d1f");
			public const string Alert_DescriptionFieldName = "Alert Description";
			
					
			public static readonly ID Alert_TitleFieldId = new ID("ea19cfe8-8026-497a-9652-83c1712dae9d");
			public const string Alert_TitleFieldName = "Alert Title";
			
					
			public static readonly ID IsActiveFieldId = new ID("c6f7c6c4-74ef-4ae5-84da-b7a0fa159316");
			public const string IsActiveFieldName = "IsActive";
			
					
			public static readonly ID SeverityFieldId = new ID("891f95ce-edbe-496c-a34b-2e0fcb085289");
			public const string SeverityFieldName = "Severity";
			
					
			public static readonly ID Valid_FromFieldId = new ID("a08ea501-d339-4f3d-9da3-cbff8088c76c");
			public const string Valid_FromFieldName = "Valid From";
			
					
			public static readonly ID Valid_ToFieldId = new ID("5758f22c-2394-42ae-94e8-05913ea009c8");
			public const string Valid_ToFieldName = "Valid To";
			
			

	}

	
	/// <summary>
	/// _Alert
	/// <para></para>
	/// <para>Path: /sitecore/templates/ProjectPortal/Feature/Alert/_Alert</para>	
	/// <para>ID: fce37f72-5db6-4ba6-9591-2ef80648a46e</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_AlertConstants.TemplateIdString)] //, Cachable = true
	public partial class _Alert  : GlassBase, I_Alert 
	{
	   
						/// <summary>
				/// The Alert Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 413bae14-4b52-4429-96cb-eb84d3841d1f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_AlertConstants.Alert_DescriptionFieldName)]
				public virtual string Alert_Description  {get; set;}
					
						/// <summary>
				/// The Alert Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ea19cfe8-8026-497a-9652-83c1712dae9d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_AlertConstants.Alert_TitleFieldName)]
				public virtual string Alert_Title  {get; set;}
					
						/// <summary>
				/// The IsActive field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: c6f7c6c4-74ef-4ae5-84da-b7a0fa159316</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_AlertConstants.IsActiveFieldName)]
				public virtual bool IsActive  {get; set;}
					
						/// <summary>
				/// The Severity field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// <para>Field ID: 891f95ce-edbe-496c-a34b-2e0fcb085289</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_AlertConstants.SeverityFieldName)]
				public virtual string Severity  {get; set;}
					
						/// <summary>
				/// The Valid From field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: a08ea501-d339-4f3d-9da3-cbff8088c76c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_AlertConstants.Valid_FromFieldName)]
				public virtual DateTime Valid_From  {get; set;}
					
						/// <summary>
				/// The Valid To field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: 5758f22c-2394-42ae-94e8-05913ea009c8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_AlertConstants.Valid_ToFieldName)]
				public virtual DateTime Valid_To  {get; set;}
					
			
	}
}
